# roles/default-gate/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "RedHat.yml"
    - "default.yml"
  tags: default-gate

- name: Remove the NAT Default-gateway on interface
  shell: nmcli con modify {{default-gate_NAT}} ipv4.never-default true
  tags: default-gate

- name: Configuring new Default-gateway
  shell: nmcli con modify {{default-gate_LAN}} ipv4.never-default false
  tags: default-gate

- name: Add Default-gateway
  shell: nmcli con modify {{default-gate_LAN}} ipv4.gateway {{default-gate_ADDR}}
  tags: default-gate

- name: Ensure service is started
  service:
    name: network.service
    state: started
    enabled: true
  tags: default-gate
